# Generated by Django 4.2.7 on 2023-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
