# Generated by Django 4.2.7 on 2023-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_price_alter_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='Test'),
            preserve_default=False,
        ),
    ]
